version: '3'

services:

  mainapp:
    container_name: mainapp
    restart: always
    build: ./mainapp
    ports:
      - "8000:8000"
    command: gunicorn -c gunicorn.ini mainapp.application:app
  
  reverseapp:
    container_name: reverseapp
    restart: always
    build: ./reverseapp
    ports:
      - "8001:8001"
    depends_on:
      - mainapp
    command: gunicorn -c gunicorn.ini reverseapp.application:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - reverseapp

